name: PowerShell - Linux

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  linux-test:
    name: Setup test in Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install zstd
        shell: pwsh
        run: |
          apt update
          apt install zstd -y
      - name: Run setup script
        shell: pwsh
        run: |
          ./setup.ps1 -Silent -Model codegen-350M-multi -DebugMode NotRemove -Verbose;
          if (-not $?) {
            Write-Error -Message "Setup failed" | Out-Null;
          }
